site_name: Windows Terminal Quake
site_author: flyingpie

docs_dir: 'pages'
site_dir: 'docs'

nav:
- Getting Started:
  - Direct Download: 'getting-started/direct-download.md'
  - Get From Scoop: 'getting-started/get-from-scoop.md'
  - Build (Cake): 'getting-started/build-cake.md'
  - Build (Visual Studio): 'getting-started/build-vs.md'

- Settings:
  - Always On Top: settings/always-on-top.md
  - Command Line Parameters: settings/command-line-parameters.md
  - Disable When Active App Is In Fullscreen: settings/disable-when-active-app-is-in-fullscreen.md
  - Hide On Focus Lost: settings/hide-on-focus-lost.md
  - Hotkeys: settings/hotkeys.md
  - Notifications: settings/notifications.md
  - Opacity: settings/opacity.md
  - Prefer Monitor: settings/prefer-monitor.md
  - Size and Align: settings/size-and-align.md
  - Start Hidden: settings/start-hidden.md
  - Toggle Animation: settings/toggle-animation.md

- Misc:
  - Changelog: misc/changelog.md
  - Reporting Issues: misc/reporting-issues.md

theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicon.ico
  features:
    - navigation.sections
  font: false
  highlightjs: true
  hljs_languages:
    - bash
    - powershell
  icon:
    repo: fontawesome/brands/github
  logo: assets/favicon.png
  palette:
    scheme: slate
    primary: blue

repo_name: windows-terminal-quake
repo_url: http://github.com/flyingpie/windows-terminal-quake

extra_javascript:
  - assets/highlight/highlight.pack.js
  - assets/config.js
extra_css:
  - assets/highlight/styles/vs2015.css
  - assets/styles.css

markdown_extensions:
  - sane_lists
  - pymdownx.highlight:
      use_pygments: false
